### ISSUE TITLE
Plugin error - prof_omemo_plugin.prof_on_iq_stanza_receive():return value undefined, expected boolean

### ISSUE THREAD

**Issue by BastiTee** [ReneVolution/profanity-omemo-plugin#31]
Hi Rene,

I have a similar issue like #11 #12 #21 #25 with the differnece that it also breaks with the HEAD of your plugin. 

The error message in the log:
```
13/09/2017 13:35:45: prof: INF: ProfOmemoPlugin - Bundle update detected.
13/09/2017 13:35:45: prof: INF: ProfOmemoPlugin - Bundle Information received.
13/09/2017 13:35:45: prof: INF: ProfOmemoPlugin - Unwrapping bundle info.
13/09/2017 13:35:45: prof: ERR: Plugin error - prof_omemo_plugin.prof_on_iq_stanza_receive(): return value undefined, expected boolean
13/09/2017 13:35:45: stderr: ERR: Traceback (most recent call last):
13/09/2017 13:35:45: stderr: ERR:   File "/root/.local/share/profanity/plugins/prof_omemo_plugin.py", line 128, in func_wrapper
13/09/2017 13:35:45: stderr: ERR:     return func(*args, **kwargs)
13/09/2017 13:35:45: stderr: ERR:   File "/root/.local/share/profanity/plugins/prof_omemo_plugin.py", line 357, in prof_on_iq_stanza_receive
13/09/2017 13:35:45: stderr: ERR:     _handle_bundle_update(stanza)
13/09/2017 13:35:45: stderr: ERR:   File "/root/.local/share/profanity/plugins/prof_omemo_plugin.py", line 205, in _handle_bundle_update
13/09/2017 13:35:45: stderr: ERR:     bundle_info = xmpp.unpack_bundle_info(stanza)
13/09/2017 13:35:45: stderr: ERR:   File "/root/.local/lib/python2.7/site-packages/profanity_omemo_plugin-0.0.1-py2.7.egg/profanity_omemo_plugin/xmpp.py", line 149, in unpack_bundle_info
13/09/2017 13:35:45: stderr: ERR:     device_id = items_node.attrib['node'].split(':')[-1]
13/09/2017 13:35:45: stderr: ERR: AttributeError: 'NoneType' object has no attribute 'attrib'
```
I am using libmesode 0.9.1 profanity 0.5.1 and omemo-plugin 0.1.1 all compiled from source. I have a docker container where this is reproducable at https://github.com/BastiTee/dockerfiles/blob/f6ec1ea6a4226b7074b2d8d748bc6413185f0717/profanity-omemo/Dockerfile

After starting profanity I run... 
```
/connect ...
/plugins load prof_omemo_plugin.py
```
... and that's when the error occurs. 

Glad if I can provide more info. Thanks!

**Comment by BastiTee** [comment]
I keep getting this error with 
- [libmesode 0.9.1 profanity 0.5.1 and omemo-plugin HEAD](https://github.com/BastiTee/dockerfiles/blob/386b56e29ea467eb9f10c98ca70c3e9420d630c0/profanity-omemo/Dockerfile)
- [libmesode 0.9.1 profanity HEAD and omemo-plugin HEAD](https://github.com/BastiTee/dockerfiles/blob/b30e3287e294b2d6041c4cf5dddd9a24cc4bbb52/profanity-omemo/Dockerfile)

**Comment by BastiTee** [comment]
Okay, I debugged through it and the problem is that you try to extract a device ID by splitting the node-attribute at `:` of `<items/>` in my IQ:
```
<iq id="value" type="result" to="me@home/profanity" from="me@home">
    <pubsub xmlns="http://jabber.org/protocol/pubsub">
        <items node="eu.siacs.conversations.axolotl.devicelist">
            <item id="1">
                <list xmlns="eu.siacs.conversations.axolotl"><device id="47111337"/></list>
            </item>
        </items>
    </pubsub>
</iq>
```
That breaks because my id is in the first item element as separate element and `node` has no `:` in it. I can work around by adding this code around the [source line](https://github.com/ReneVolution/profanity-omemo-plugin/blob/78be0c8367c6379829986755c0d1da287c031234/src/profanity_omemo_plugin/xmpp.py#L184).

I worked around this particular issue by setting the device ID manually but then it will fail with even more errors related to my IQ:
```
15/09/2017 13:12:51: stderr: ERR: Traceback (most recent call last):
15/09/2017 13:12:51: stderr: ERR:   File "/home/st/.local/share/profanity/plugins/prof_omemo_plugin.py", line 178, in func_wrapper
15/09/2017 13:12:51: stderr: ERR:     return func(*args, **kwargs)
15/09/2017 13:12:51: stderr: ERR:   File "/home/st/.local/share/profanity/plugins/prof_omemo_plugin.py", line 489, in prof_on_iq_stanza_receive
15/09/2017 13:12:51: stderr: ERR:     _handle_bundle_update(stanza)
15/09/2017 13:12:51: stderr: ERR:   File "/home/st/.local/share/profanity/plugins/prof_omemo_plugin.py", line 304, in _handle_bundle_update
15/09/2017 13:12:51: stderr: ERR:     bundle_info = xmpp.unpack_bundle_info(stanza)
15/09/2017 13:12:51: stderr: ERR:   File "/home/st/.local/lib/python2.7/site-packages/profanity_omemo_plugin-0.0.1-py2.7.egg/profanity_omemo_plugin/xmpp.py", line 194, in unpack_bundle_info
15/09/2017 13:12:51: stderr: ERR:     signedPreKeyPublic_node = find_node(bundle_node, 'signedPreKeyPublic', ns=NS_OMEMO)
15/09/2017 13:12:51: stderr: ERR:   File "/home/st/.local/lib/python2.7/site-packages/profanity_omemo_plugin-0.0.1-py2.7.egg/profanity_omemo_plugin/xmpp.py", line 59, in find_node
15/09/2017 13:12:51: stderr: ERR:     node = xml.find('.//{%s}%s' % (ns, name))
15/09/2017 13:12:51: stderr: ERR: AttributeError: 'NoneType' object has no attribute 'find'
```

So I assume this is a general misconfiguration on my end?

**Comment by ReneVolution** [comment]
Hey @BastiTee, thanks a lot for investigating here.
From the error message, it looks like I can't "unpack" your bundle info, because for some reason, `bundle_node` could not be found. Any chance you could send me the bundle info you receive right before the crash happens?

**Comment by BastiTee** [comment]
If I understand correct, it's this:

```
<iq id="value" type="result" to="me@home/profanity" from="me@home">
    <pubsub xmlns="http://jabber.org/protocol/pubsub">
        <items node="eu.siacs.conversations.axolotl.devicelist">
            <item id="1">
                <list xmlns="eu.siacs.conversations.axolotl"><device id="47111337"/></list>
            </item>
        </items>
    </pubsub>
</iq>
```

**Comment by BastiTee** [comment]
By the way: I can exclude server issues. I managed to talk OMEMO using Conversation and Pidgin with Lurch.

**Comment by ReneVolution** [comment]
What you have sent is a device list response. We need to look at the bundle info `eu.siacs.conversations.axolotl.bundle` stanza.

**Comment by ReneVolution** [comment]
Like this one: https://github.com/ReneVolution/profanity-omemo-plugin/blob/master/tests/fixtures/stanzas/iq_bundle_info.xml.

**Comment by BastiTee** [comment]
```
15/09/2017 14:53:56: prof: INF: ProfOmemoPlugin - Device List update detected.
15/09/2017 14:53:56: prof: INF: ProfOmemoPlugin - Received devicelist update from alice@bob.org
15/09/2017 14:53:56: prof: WRN: api_chat_show_themed failed, could not find chat window for %s
15/09/2017 14:53:56: prof: INF: ProfOmemoPlugin - Adding Device ID's: [1500470632] for alice@bob.org.
15/09/2017 14:53:56: prof: INF: ProfOmemoPlugin - Adding own devices
15/09/2017 14:53:56: prof: INF: ProfOmemoPlugin - Device List update done.
15/09/2017 14:53:56: xmpp: DBG: RECV: <iq id="51e881a0-af7b-440e-8c0b-7d521c61806f" type="result" to="alice@bob.org/profanity" from="alice@bob.org"><pubsub xmlns="http://jabber.org/protocol/pubsub"><publish node="eu.siacs.conversations.axolotl.bundles:1500470632"><item id="5E175324EDF4"/></publish></pubsub></iq>
15/09/2017 14:53:56: prof: DBG: iq stanza handler fired
15/09/2017 14:53:56: prof: INF: ProfOmemoPlugin - Received IQ: <iq id="51e881a0-af7b-440e-8c0b-7d521c61806f" type="result" to="alice@bob.org/profanity" from="alice@bob.org"><pubsub xmlns="http://jabber.org/protocol/pubsub"><publish node="eu.siacs.conversations.axolotl.bundles:1500470632"><item id="5E175324EDF4"/></publish></pubsub></iq>
15/09/2017 14:53:56: prof: INF: ProfOmemoPlugin - Bundle update detected.
15/09/2017 14:53:56: prof: INF: ProfOmemoPlugin - Bundle Information received.
15/09/2017 14:53:56: prof: INF: ProfOmemoPlugin - Unwrapping bundle info.
15/09/2017 14:53:56: prof: ERR: Plugin error - prof_omemo_plugin.prof_on_iq_stanza_receive(): return value undefined, expected boolean
15/09/2017 14:53:56: stderr: ERR: Traceback (most recent call last):
15/09/2017 14:53:56: stderr: ERR:   File "~/.local/share/profanity/plugins/prof_omemo_plugin.py", line 178, in func_wrapper
15/09/2017 14:53:56: stderr: ERR:     return func(*args, **kwargs)
15/09/2017 14:53:56: stderr: ERR:   File "~/.local/share/profanity/plugins/prof_omemo_plugin.py", line 489, in prof_on_iq_stanza_receive
15/09/2017 14:53:56: stderr: ERR:     _handle_bundle_update(stanza)
15/09/2017 14:53:56: stderr: ERR:   File "~/.local/share/profanity/plugins/prof_omemo_plugin.py", line 304, in _handle_bundle_update
15/09/2017 14:53:56: stderr: ERR:     bundle_info = xmpp.unpack_bundle_info(stanza)
15/09/2017 14:53:56: stderr: ERR:   File "~/.local/lib/python2.7/site-packages/profanity_omemo_plugin-0.0.1-py2.7.egg/profanity_omemo_plugin/xmpp.py", line 184, in unpack_bundle_info
15/09/2017 14:53:56: stderr: ERR:     device_id = items_node.attrib['node'].split(':')[-1]
15/09/2017 14:53:56: stderr: ERR: AttributeError: 'NoneType' object has no attribute 'attrib'
```
or
```
<iq id="51e881a0-af7b-440e-8c0b-7d521c61806f" type="result" to="alice@bob.org/profanity" from="alice@bob.org">
    <pubsub xmlns="http://jabber.org/protocol/pubsub">
        <publish node="eu.siacs.conversations.axolotl.bundles:1500470632"><item id="5E175324EDF4"/></publish>
    </pubsub>
</iq>
```

**Comment by ReneVolution** [comment]
Oh .. thanks ... that looks interesting. Why is there nothing in the bundle??? 
Do you know from what client this is coming?

Note to self ... let this gracefully fail ...

**Comment by BastiTee** [comment]
Dunno what you mean. You have to help me out here. 
The error is reproducable in this order:

- Opeing profanity 
- /plugins load prof_omemo_plugin.py 
- /connect alice@bob.org
>>> now.

Afaik at this stage only server and my client are involved. or does that happen due to my other contacts? 
If yes: The contact in my list thats usually only does not have omemo support in his client.

**Comment by BastiTee** [comment]
Did you had the chance to try it through my [docker image](https://github.com/BastiTee/dockerfiles/blob/master/profanity-omemo/Dockerfile)? That way you could clarify – if everything works fine on your end – if it's "environmental" or not.

**Comment by BastiTee** [comment]
Another thing i've tested: I removed all my buddies from my roster, to see if it's related to contacs but the behaviour stays the same.

**Comment by ReneVolution** [comment]
I need to check where this XMPP stanza comes from and what it means:

```
<iq id="51e881a0-af7b-440e-8c0b-7d521c61806f" type="result" to="alice@bob.org/profanity" from="alice@bob.org">
    <pubsub xmlns="http://jabber.org/protocol/pubsub">
        <publish node="eu.siacs.conversations.axolotl.bundles:1500470632"><item id="5E175324EDF4"/></publish>
    </pubsub>
</iq>
```

It is not how I expect the bundles stanza to look like. Therefore I asked if you know what client application (Conversations, Pidgin,...) this comes from.

**Comment by BastiTee** [comment]
As I said. I try to run your plugin. So profanity HEAD it is. No other clients involved imho.

**Comment by ReneVolution** [comment]
Ok. I have made the bundle unpacking more robust to incomplete bundle info messages. Can you try with the current `profanity-omemo-plugin` HEAD?

**Comment by BastiTee** [comment]
Hey, thanks. That gets me until here.
Then
```
15/09/2017 17:39:35: prof: INF: ProfOmemoPlugin - Bundle update detected.
15/09/2017 17:39:35: prof: INF: ProfOmemoPlugin - Bundle Information received.
15/09/2017 17:39:35: prof: INF: ProfOmemoPlugin - Unwrapping bundle info.
15/09/2017 17:39:35: prof: WRN: ProfOmemoPlugin - Could not unpack bundle info. Node {0} not found.
15/09/2017 17:39:35: prof: ERR: Plugin error - prof_omemo_plugin.prof_on_iq_stanza_receive(): return value undefined, expected boolean
15/09/2017 17:39:35: stderr: ERR: Traceback (most recent call last):
15/09/2017 17:39:35: stderr: ERR:   File "/root/.local/share/profanity/plugins/prof_omemo_plugin.py", line 178, in func_wrapper
15/09/2017 17:39:35: stderr: ERR:     return func(*args, **kwargs)
15/09/2017 17:39:35: stderr: ERR:   File "/root/.local/share/profanity/plugins/prof_omemo_plugin.py", line 489, in prof_on_iq_stanza_receive
15/09/2017 17:39:35: stderr: ERR:     _handle_bundle_update(stanza)
15/09/2017 17:39:35: stderr: ERR:   File "/root/.local/share/profanity/plugins/prof_omemo_plugin.py", line 306, in _handle_bundle_update
15/09/2017 17:39:35: stderr: ERR:     sender = bundle_info.get('sender')
15/09/2017 17:39:35: stderr: ERR: AttributeError: 'NoneType' object has no attribute 'get'
```
... suppse the exception is catched, but the object still none, so no [map call possible](https://github.com/ReneVolution/profanity-omemo-plugin/blob/4258d5aa4b90aa2549ef2c3bb480a270eb94e853/deploy/prof_omemo_plugin.py#L306). 

Should be sth. like
```
sender = bundle_info.get('sender') if bundle_info else "?"
device_id = bundle_info.get('device') if bundle_info else "?"
```

Got no more time for testing myself for now. Sorry. Would have created a pull request otherwise.

**Comment by ReneVolution** [comment]
Ok. I have handled this with the latest commit. Let me know once you have time again to test.

**Comment by BastiTee** [comment]
Thanks René. That solved the issue. Have a nice weekend. 
![screenshot from 2017-09-16 09-51-39](https://user-images.githubusercontent.com/7995100/30510463-da54a1f0-9ac4-11e7-973f-41f6159004bd.png)
