### ISSUE TITLE
Cannot send encrypted message

### ISSUE THREAD

**Issue by aereaux** [ReneVolution/profanity-omemo-plugin#39]
When I try to send an encrypted message, the message is sent, and it shows the @ symbol before it (which I assume is supposed to mean that it was encrypted).  However, it shows on my other client (conversations) as unencrypted, as well as on the receiver's side, and "Last message was sent unencrypted." is shown in the chat window before the message.  The log contains this:
```
13/02/2018 17:06:40: prof: ERR: ProfOmemoPlugin - Could not encrypt message
Traceback (most recent call last):
  File "/home/user/.local/share/profanity/plugins/prof_omemo_plugin.py", line 364, in prof_on_message_stanza_send
    encrypted_stanza = xmpp.encrypt_stanza(stanza)
  File "/home/user/.local/lib/python3.6/site-packages/profanity_omemo_plugin-0.0.1-py3.6.egg/profanity_omemo_plugin/xmpp.py", line 86, in encrypt_stanza
    account, resource = jid.rsplit('/', 1)
ValueError: not enough values to unpack (expected 2, got 1)
```
Let me know if any other information needs to be provided.

**Comment by aereaux** [comment]
So after further testing, I figured out that if I have already started a conversation (with conversations), there is no error message or unencrypted warning when I try to send a message.  However, the person I am having a conversation with says that they did not get the message, and I do not see it on my other client (conversations).  In addition, at the top of the window it has the full jid (user@domain/resource).

**Comment by paullouisageneau** [comment]
Please check with the fixes in #44, it should solve your issue.
